providers = ["python"]

[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r src/backend/requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn --chdir src/backend app:app --log-file -"
